env                 = "dev"
target_account_id   = "12345"
domain_name         = "BU-edv-d.domain.com"
newrelic_app_name   = "email-delivery-verification-d"
newrelic_account_id = "123"
auth_callback_url   = "https://BU-edv-d.domain.com/auth_callback"
