region         = "us-east-1"
bucket         = "tf-BU-gitlab-prd-us-east-1-12345"
dynamodb_table = "terraform-lock"
key            = "BU/123456.us-east-1.BU-edv-prd.tfstate"
kms_key_id     = "alias/source-tf-BU"
